### ISSUE TITLE
Battery Icon Fix is not working Correctly

### ISSUE THREAD

**Issue by rakshit087** [pop-os/gnome-shell-extension-pop-battery-icon-fix#6]
**Distribution (run `cat /etc/os-release`):**
 20.10
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
None

**Issue/Bug Description:**
The battery icon is not updating according to curent battery level.

**Steps to reproduce (if you know):**

1. Login to your system
2. You will notice that the battery icon shows that battery is fully charged
3. If you are on the lock screen it will work as intended.

**Expected behavior:**

Battery Icon updates according to current battery level.

**Other Notes:**

I am attaching Screen Shots of the same 
![image](https://user-images.githubusercontent.com/50898928/103621803-c58e7d00-4f5b-11eb-8fc3-2158bc52672d.png)

![image](https://user-images.githubusercontent.com/50898928/103622027-1d2ce880-4f5c-11eb-94b1-44f54268cf64.png)

**Comment by EthanITA** [comment]
I confirm this issue, the reproduction in my case is when I unlock my laptop after it goes to sleep/suspension

**Comment by rakshit087** [comment]
I also noticed that it works perfectly above 60%.

**Comment by tnfru** [comment]
Also recently started happening to me.

**Comment by Rebreda** [comment]
Still broken for me as well, no rhyme or reason.

**Comment by rakshit087** [comment]
I think it's fixed now
